name: test-and-connect-publish
on:
   push:
     branches: [feature_shammi]
   pull_request:
     branches: [feature_shammi]
    
jobs:
    test-and-connect-publish:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2

        - uses: r-lib/actions/setup-pandoc@v2

        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: 4.2.3
            use-public-rspm: true
        - name: Test Shiny App
          shell: Rscript {0}
          run: |
            shinyapptest::app()
        - name: Create manifest.json
          shell: Rscript {0}
          run: |
            rsconnect::writeManifest()
